/* ============================================================
   MCRI People Portal - Supabase PostgreSQL setup

   Run this in Supabase -> SQL Editor. Safe to run more than once:
   it creates nothing that already exists and only seeds an empty table.

   The quoted "PascalCase" names are not decoration. PostgreSQL folds
   unquoted identifiers to lower case, while Entity Framework quotes the
   names from AppDbContext ("People", "FirstName", ...). The two only line
   up if the table is created with the quotes, exactly as below.
   ============================================================ */

/* ---------- 1. What is there now? ----------
   Run this first. If the column list at the bottom does not match this
   script, the app will fail with 42P01 (relation does not exist) or 42703
   (column does not exist). */

SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE lower(table_name) = 'people' AND table_schema = 'public'
ORDER BY table_name, ordinal_position;


/* ---------- 2. Table ---------- */

CREATE TABLE IF NOT EXISTS public."People"
(
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName"             varchar(100) NOT NULL,
    "LastName"              varchar(100) NOT NULL,
    "PersonType"            varchar(20)  NOT NULL,
    "DepartmentOrProgramme" varchar(150) NOT NULL,
    "Email"                 varchar(200) NOT NULL,
    "FunFact"               varchar(500),
    "ImageUrl"              varchar(500),

    CONSTRAINT "PK_People" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_People_PersonType" CHECK ("PersonType" IN ('Student', 'Employee'))
);


/* ---------- 3. Columns added after the first version ----------
   ImageData holds the profile photo itself; the portal serves it from
   GET api/people/{id}/image rather than from a storage bucket. */

ALTER TABLE public."People" ADD COLUMN IF NOT EXISTS "ImageData"        bytea;
ALTER TABLE public."People" ADD COLUMN IF NOT EXISTS "ImageContentType" varchar(100);
ALTER TABLE public."People" ADD COLUMN IF NOT EXISTS "Gender"           varchar(50);
ALTER TABLE public."People" ADD COLUMN IF NOT EXISTS "Cohort"           varchar(100);
ALTER TABLE public."People" ADD COLUMN IF NOT EXISTS "Phase"            varchar(100);


/* ---------- 4. Index ----------
   Helps the "filter by Student or Employee" feature. */

CREATE INDEX IF NOT EXISTS "IX_People_PersonType" ON public."People" ("PersonType");


/* ---------- 5. Seed data ----------
   Only runs when the table is empty, so re-running this file never
   duplicates rows. Placeholders - replace with the real MCRI list. */

INSERT INTO public."People"
    ("FirstName", "LastName", "PersonType", "DepartmentOrProgramme", "Email", "FunFact")
SELECT * FROM (VALUES
    ('Benon',   'Marava',    'Employee', 'Software Engineering',             'benon.marava@mcri.org',            'Runs the SDLC workshop this portal was built for.'),
    ('Tendai',  'Moyo',      'Employee', 'Data & Analytics',                'tendai.moyo@mcri.org',             'Can name every SQL join type from memory.'),
    ('Grace',   'Chikwanha', 'Employee', 'Human Resources',                 'grace.chikwanha@mcri.org',         'Has interviewed more than 500 candidates.'),
    ('Farai',   'Nyathi',    'Employee', 'Research Operations',             'farai.nyathi@mcri.org',            'Keeps a spreadsheet of every coffee tried.'),
    ('Rudo',    'Mutasa',    'Student',  'BSc Computer Science',            'rudo.mutasa@students.mcri.org',    'Built a first website at age eleven.'),
    ('Kudzai',  'Banda',     'Student',  'BSc Information Systems',         'kudzai.banda@students.mcri.org',   'Plays bass in a weekend band.'),
    ('Nyasha',  'Dube',      'Student',  'BSc Data Science',                'nyasha.dube@students.mcri.org',    'Once won a hackathon with a team of one.'),
    ('Tapiwa',  'Sibanda',   'Student',  'Diploma in Software Development', 'tapiwa.sibanda@students.mcri.org', 'Speaks four languages.'),
    ('Chiedza', 'Marufu',    'Student',  'BSc Computer Science',            'chiedza.marufu@students.mcri.org', 'Volunteers teaching kids to code on Saturdays.'),
    ('Simba',   'Ncube',     'Student',  'BSc Information Systems',         'simba.ncube@students.mcri.org',    'Collects vintage keyboards.')
) AS seed
WHERE NOT EXISTS (SELECT 1 FROM public."People");


/* ---------- 6. Quick checks, one per endpoint ---------- */

-- GET api/people
SELECT * FROM public."People" ORDER BY "FirstName", "LastName";

-- GET api/people?search=gra
SELECT * FROM public."People"
WHERE lower("FirstName") LIKE '%gra%' OR lower("LastName") LIKE '%gra%';

-- GET api/people?personType=Student
SELECT * FROM public."People" WHERE "PersonType" = 'Student';

-- GET api/people/1
SELECT * FROM public."People" WHERE "Id" = 1;
